# Generated by Django 4.2.2 on 2023-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpage_content_blogpage_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
