# Generated by Django 4.2.2 on 2023-07-10 18:58

from django.db import migrations, models
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='contents',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.TextBlock(blank=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True)), ('video_url', wagtail.blocks.URLBlock(blank=True)), ('link', wagtail.blocks.URLBlock(blank=True))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
