# Generated by Django 4.2.2 on 2023-07-05 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='researchpage',
            name='abstract',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
