# Generated by Django 4.2.2 on 2023-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpage',
            name='code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpage',
            name='paper_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpage',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
